name: Deploy Vulnerable Application                                  # workflow name

on:
  push:
    branches:
      - main

jobs:
  run-sast-workflow:
    uses: ./.github/workflows/run-sast-tools.yml

  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    needs: run-sast-workflow
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dso-cicd-maximo-rochamejia"
          heroku_email: "maximroc@gmail.com"
          remote_branch: "master"
          usedocker: true
